### PR TITLE
prop-types should be a dependency

### PR DESCRIPTION
**Pull request by Noitidart**

### CODE REVIEW

**Comment by rajsuvariya** [comment]
Thank you for spending to fix this repo. But I am not sure if this is a requirement. I am able to use it without this dependency.

**Comment by Noitidart** [comment]
Understood, thanks! :) Im getting a new `react-native init` going to test right now, my computer is a bit slow this morning.

**Comment by rajsuvariya** [comment]
Yeah, no issues. Can you connect with me over hangout? My email id is
rajsuvariya@gmail.com

-- 
Raj Suvariya
*Android / React Native Developer*
Kuliza Technologies, Bangalore
Medium : https://medium.com/@rajsuvariya
m: +91-9099809050
<https://www.facebook.com/profile.php?id=100006523120386>
<https://twitter.com/RAJ_SUVARIYA>
<https://www.linkedin.com/in/rajpatel039/>

**Comment by Noitidart** [comment]
Connecting right away!! :)

**Pull request closed without merging**
